version: '2'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JUPYTER_DOCKER_IMAGE: jupyter/base-notebook
        JUPYTER_DOCKER_IMAGE_VERSION: python-3.11
    #image: jupyter/minimal-notebook:latest
    container_name: jupyter
    hostname: jupyterlab
    restart: unless-stopped
    expose:
      - 8888
    volumes:
      - $HOME/Documents/dev/jupyterlab:/home/jovyan
      #- ~/.config/jupyter/jupyter_notebook_config.py:/srv/jupyterhub/jupyterhub_config.py:ro
      #- ~/.config/jupyter/jupyter_server_config.py:/home/jovyan/.jupyter/jupyter_server_config.py
    environment:
      - GRANT_SUDO=yes

networks:
  default:
    external: true
    name: webproxy