version: "2"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - /home/pi/.ssl:/etc/nginx/ssl:ro
      - /home/pi/.config/nginx:/etc/nginx/conf.d:ro
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    extra_hosts:
        - "host.docker.internal:host-gateway"

networks:
  default:
    external: true
    name: webproxy
